- .github/workflows/conventional-pr.yml
- Package.resolved
- Package.swift
- Sources/Noora/Utilities/Spinner.swift
- Tuist/Config.swift
- I'm removing `CombineX` and `Asynchrone`, which are not really needed for this project. They are heavy dependencies and the functionality that we use from them can also be replicated with `Foundation`.
- Since we use SPM as a build tool, we don't need a `Config.swift` file, so I'm removing it.
> chore: Remove unnecessary dependencies and `Config.swift`

- Sources/Noora/Components/SingleChoicePrompt.swift
- Sources/Noora/Noora.swift
- Tests/NooraTests/Components/SingleChoicePromptTests.swift
- docs/content/components/prompts/single-choice.md
I noticed "SingleChoicePrompt" is designed to only support list of options resolved at compile time. However, this is restrictive in cases where the options are resolved at runtime. This PR extends the API to bring that flexibility.
> feat: Support runtime options in the SingleChoicePrompt

- Sources/Noora/Components/CollapsibleStep.swift
- Sources/Noora/Components/ProgressStep.swift
- Sources/Noora/Noora.swift
- Sources/Noora/NooraMock.swift
- Sources/examples-cli/Commands/ProgressStepCommand.swift
- Tests/NooraTests/Components/CollapsibleStepTests.swift
- Tests/NooraTests/Components/ProgressStepTests.swift
- docs/content/components/step/progress.md
When I attempted to use the new collapsible component I noticed the closure passed to the `task` closure is non-escaping, limiting the flexibility of the caller. This PR fixes it.
> fix: make the closure passed to the task closure @escaping

- Sources/Noora/NooraMock.swift
- Tests/NooraTests/Utilities/NooraMockTests.swift
As discussed [here](https://github.com/tuist/tuist/pull/7334#discussion_r1963861334), I'm dropping the prefix when recording stdout events in `NooraMock`.
> fix: not include prefix for stdout lines recorded by the mock

- Sources/Noora/Components/SingleChoicePrompt.swift
- Sources/Noora/Utilities/Terminal.swift
- Tests/NooraTests/Components/SingleChoicePromptTests.swift
- Tests/NooraTests/Mocks/MockTerminal.swift
Hi! Love the project, I'm hoping to retire [SwiftTUI](https://github.com/finnvoor/SwiftTUI) in favor of Noora for tools like [xcc](https://github.com/finnvoor/xcc). There's just a few things holding me back from switching, so here's a PR for one of them:
https://github.com/user-attachments/assets/21b8d0bd-2fac-4c4a-bc72-a2cbd2a721f7
When the number of options in SingleChoicePrompt exceeds the number of rows in your terminal, it will now render as a scrolling list.
Currently `Renderer` ends all renders with a newline. It would be nice if this was changed so the list could take the full terminal height, but I left this for a future PR to keep this one simple. Please let me know if you have any feedback!
Remaining:
> feat: scroll SingleChoicePrompt when larger than terminal height

- Sources/Noora/Utilities/KeyStrokeListener.swift
- docs/.vitepress/config.mjs
- docs/content/utilities/keystroke-listener.md
As part of building the new get started experience, where I reused the login service, I noticed we ended up taking the user to the browser without any context. A better experience would consist of asking the user to press "enter" after reading that we are going to take them to the browser to complete the authentication.
Since we have the utility in Noora to listen to keystrokes, I'm making it public and documenting it for anyone to use.
> feat: make `KeyStrokeListener` public

- Sources/Noora/Noora.swift
- Sources/Noora/Utilities/Renderer.swift
- mise/tasks/test-linux
Allow passing a custom `Rendering`/`KeyStrokeListening` to `Noora`, enabling amazing things like [this](https://mastodon.social/@finnvoorhees/114072798657337663).
> feat: allow custom renderer and keystroke listener in Noora

- Sources/Noora/Components/SingleChoicePrompt.swift
- Sources/Noora/Noora.swift
- Tests/NooraTests/Components/SingleChoicePromptTests.swift
- docs/content/components/prompts/single-choice.md
Adds an option `autoSelectSingle` that, when enabled, automatically picks the first item from options when options only contains one item, skipping the wait for user selection.
This is something I use in `xcc`, and the benefit over just handling this in `xcc` is that the output is still rendered in the SingleChoicePrompt style, making the output consistent whether an option is manually selected or auto selected.
Example: The `main` branch is auto selected
https://github.com/user-attachments/assets/b150f0f0-4eba-4140-bc60-d3c302c17f8b
> feat: add autoSelectSingle option to SingleChoicePrompt

- Sources/Noora/Noora.swift
- Sources/Noora/NooraMock.swift
In a recent PR we scoped the lifecycle of `Renderer` to the lifecycle of `Noora`, and that caused the rendering of components to override previous renders. `Renderer` was designed to have its lifetime scope to every component, and therefore we should be creating a new instance for every render. This PR fixes it.
> fix: component overriding previous renders

- Sources/Noora/Theme.swift
I picked those colors using a dark background as a reference and they turned out to have a terrible contract in light themes. This PR changes the `secondary`, `accent`, and `success` colors of the main theme to have a good contrast in dark and light backgrounds.
> fix: improve contrast of secondary, accent, and success colors in the default theme.

- Sources/Noora/Noora.swift
- Sources/Noora/NooraMock.swift
- Tests/NooraTests/Components/SingleChoicePromptTests.swift
- Tests/NooraTests/Utilities/TerminalTextTests.swift
I messed up with the extension for `Noora` causing an infinite recursion in the function to render a single choice prompt component. This PR fixes it.
> fix: recursion in the extension to render single choice prompt component

- Sources/Noora/Noora.swift
I'm making alerts hashable so consumers can use it with data structures like `Set` to handle duplicates.
> feat: make alerts hashable

- Sources/Noora/Noora.swift
I came across a use case where I have to modify an alert collected during the lifecycle of a CLI to include additional next steps. Because the properties of alerts are private, I can't access them to create a new copy of the alert with modified values, so I'm making the properties of alerts public.
> feat: make alert properties public

- Sources/Noora/Components/Alert.swift
Alerts don't handle multi-line texts gracefully. Note how in the screenshot below how the left bars are missing for the lines of the error. This PR fixes it for the alert message/title and the next steps.
> fix: handle multi-line texts in alerts

- Sources/Noora/Components/Alert.swift
- Tests/NooraTests/Components/CompletionTests.swift
As @fortmarek noted [here](https://github.com/tuist/tuist/pull/7399#discussion_r1993029874), the copy of the warning alert is wrong. It should introduce the reader to the warnings.
> fix: improve the copy of the warning alert

- Sources/Noora/NooraMock.swift
I noticed on the `tuist/tuist` side of things that we were not resetting the recorded data, leading to the recorded output accumulating, and our test assertions being inaccurate. This PR exposes an API to reset the mock's data.
> feat: add support for resetting NooraMock's data

- Package.resolved
- Package.swift
- Sources/Noora/Utilities/TerminalText.swift
I'm adding support for a new type of component in `TerminalText`, paths:
```swift
let message: TerminalText = "Project generated at \(.path(directory))"
```
Noora will automatically format the path to be relative to the working directory to be shorter than showing the entire absolute path.
> feat: support path components in TerminalText

- cliff.toml
- renovate.json
We are doing releases when Renovate updates dependencies that are non-SPM. We should not do that because those changes have no impact in Noora itself.
This PR adjusts the Renovate configuration to apply a different convention for SPM dependency update PRs, and configures Git cliff to skip other Renovatebot PRs.
> Add commit parsers and update renovate config

- Sources/Noora/Utilities/Terminal.swift
Resolves: https://github.com/tuist/tuist/issues/7513
We should respect the ANSI color environment variables as documented [here](https://bixense.com/clicolors/):
```python
import os, sys
def has_colors():
if os.environ.get('NO_COLOR'):
return False
elif os.environ.get('CLICOLOR_FORCE'):
return True
return sys.stdout.isatty()
```
> fix: align with the ANSI color standard

- Sources/Noora/Components/ProgressBarStep.swift
- Tests/NooraTests/Components/ProgressBarStepTests.swift
The progress bar step component had a bug in its non-interactive version that [caused](https://github.com/tuist/tuist/pull/7533#discussion_r2060507574) success messages to have an extra indentation.
> fix: indentation issue in non-interactive output

- Sources/Noora/Utilities/Terminal.swift
This PR adds a simple guard to Terminal.size() to ensure it only returns a valid TerminalSize when both ws_col and ws_row are greater than zero.
> fix: Prevent divide-by-zero when terminal reports zero columns or rows

- web/js/formatters.js
- web/js/formatters.test.js
Needed for https://github.com/tuist/tuist/pull/7807#issuecomment-3062647556
Simplifies the `formatHours` function to always display time as hours only, removing the day/hour breakdown for a cleaner, more consistent format.
- Always formats as "Xh" regardless of duration (e.g., "1h", "25h", "168h")
- Rounds fractional hours to nearest whole hour using `Math.round()`
- Simplified implementation with consistent behavior across all time ranges
- Removed complex day/hour calculations for better readability
- Updated all tests to match hours-only format
- `formatHours(1.5)` → `"2h"`
- `formatHours(25.5)` → `"26h"` 
- `formatHours(168)` → `"168h"` (1 week)
- `formatHours(720)` → `"720h"` (30 days)
> feat: simplify formatHours to always show hours only

- .github/workflows/conventional-pr.yml
- Package.resolved
- cli/Sources/Noora/Noora.swift
- cli/Sources/Noora/NooraMock.swift
- cli/Sources/Noora/StandardPipelineType.swift
- docs/.vitepress/config.mjs
- docs/content/components/other.md
I was [working](https://github.com/tuist/tuist/pull/7893) on a CLI list and read interface for bundles, when I noticed the need for text output that's not captured by any of the components provided by Noora. Note that traditionally we used the Logger for that, but we agreed we'd leave logger for diagnosing purposes, while we'd treat Noora as the interface to user-facing text (UI).
To address that, I'm adding a new interface, `Noora().passthrough("...")` that outputs the given resolving the format of the provided `TerminalText` instance.
> feat: add passthrough component

- cli/Sources/Noora/Noora.swift
- cli/Sources/Noora/NooraMock.swift
- cli/Tests/NooraTests/Components/NooraTests.swift
- docs/content/components/other.md
I'm adding an interface to output a JSON given a `Codable` object.
One might thin, why not just use `.passthrough` and ask the caller to do the encoding. That works too, but by owning the encoding part, we can ensure consistent formatting, and down the road, even build an interactive version of this, where the user could type to query data in the JSON dynamically.
> feat: Add an interface to output JSON

- storybook/storybook/text_area.story.exs
- web/css/index.css
- web/css/label.css
- web/css/text-area.css
- web/lib/noora.ex
- web/lib/noora/label.ex
- web/lib/noora/text_area.ex
Adds the Text Area component from the design system:
> feat: add text area component

- storybook/storybook/text_input.story.exs
- web/lib/noora/text_input.ex
Sets the label as disabled when the text input is disabled as per the design: https://www.figma.com/design/AOrO3lGZvGvtD6hA6nIQmb/Noora-Design-System?node-id=967-2161&t=cQRoNknrxvvRxzEH-11
> fix: make label disabled when text input is disabled

- storybook/storybook/inline_dropdown.story.exs
- web/css/dropdown.css
- web/lib/noora/dropdown.ex
The `inline_dropdown` currently doesn't support an icon which we need for the QA timeline.
> feat: add icon slot to inline_dropdown

- .github/workflows/release-web.yml
the latest commit didn't get released due to a race condition:
- commit 1 published to hex, didn't commit release changes, yet
- commit 2 started
- commit 2 tried to publish to hex – with the same version as commit 1 as the changes were not committed, yet. **Fails**
- commit 1 commits changes
I think it's ok to replace the hex version as the version should get replaced almost immediately after release. Otherwise, we'd need to shuffle around the steps. That's also a possible alternative since the storybook depends on the local version of noora, but I have the feeling we might introduce a race condition of a different sort 😅
> fix: ci release race condition

- web/lib/noora/modal.ex
We also need to put the `footer` through the modal because we often want it to react to phx changes (such as disabling/enabling buttons)
> fix: modal footer not reacting to phx updates
